In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[9, 14], [17, 1], [22, 26], [25, 8, 18], [26, 11, 10], [25, 14], [25, 11, 29], [24, 26], [24, 10], [2, 6]]


In [5]:
max_length = 4
embeded_vector_size = 5
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 9 14  0  0]
 [17  1  0  0]
 [22 26  0  0]
 [25  8 18  0]
 [26 11 10  0]
 [25 14  0  0]
 [25 11 29  0]
 [24 26  0  0]
 [24 10  0  0]
 [ 2  6  0  0]]


In [19]:
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())
X = padded_reviews
y = sentiment
model.fit(X, y, epochs=50, verbose = 0)

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_13 (Flatten)            │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [21]:
weights = model.get_layer('embedding').get_weights()[0]
print(len(weights))
weights

30


array([[ 0.0155937 , -0.01652306, -0.00993268,  0.01899598,  0.04042448],
       [ 0.084135  , -0.00015117, -0.02599743, -0.03924093, -0.08628666],
       [ 0.04039057, -0.04912048, -0.01287863,  0.0431399 ,  0.07663836],
       [-0.00185834, -0.02977731, -0.0183397 , -0.03394057, -0.04729365],
       [ 0.0069868 ,  0.0411692 , -0.02328508, -0.02387772,  0.03912249],
       [ 0.00078557, -0.00586651, -0.01400677, -0.00608425,  0.01274249],
       [-0.07004505,  0.06909361,  0.06486769,  0.05864573,  0.10374824],
       [ 0.04922731,  0.02562347,  0.00364106,  0.01013369,  0.04754919],
       [ 0.01999396, -0.03125502, -0.10205138, -0.04444388, -0.05574267],
       [-0.07042129,  0.06074074,  0.05277321, -0.05943199, -0.02271672],
       [-0.00563484, -0.00886768,  0.09411017,  0.06546321, -0.02779716],
       [ 0.03929624, -0.04876298, -0.01814088, -0.02449428,  0.00187287],
       [-0.02271464,  0.01970655,  0.01822409, -0.01085745, -0.01784012],
       [ 0.03394932,  0.00193306, -0.0