In [1]:
import tensorflow_hub as hub
import tensorflow_text as text

In [2]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [3]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)
text_test = [
    'What a fantastic day it is!',
    'Coding is an art and science',
    'The weather is beautiful today',
    'Artificial intelligence is fascinating',
    'I enjoy reading books on weekends',
    'The food at that restaurant was delicious',
    'Exercise helps in staying healthy',
    'The new smartphone has amazing features',
    'Traveling to new places is exciting',
    'The concert last night was incredible'
]
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [6]:
print(text_preprocessed['input_mask'],"\n")
print(text_preprocessed['input_type_ids'],"\n")
print(text_preprocessed['input_word_ids'],"\n")

tf.Tensor(
[[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]], shape=(10, 128), dtype=int32) 

tf.Tensor(
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]], shape=(10, 128), dtype=int32) 

tf.Tensor(
[[  101  2054  1037 ...     0     0     0]
 [  101 16861  2003 ...     0     0     0]
 [  101  1996  4633 ...     0     0     0]
 ...
 [  101  1996  2047 ...     0     0     0]
 [  101  7118  2000 ...     0     0     0]
 [  101  1996  4164 ...     0     0     0]], shape=(10, 128), dtype=int32) 



In [7]:
bert_model = hub.KerasLayer(encoder_url)
bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [10]:
print(bert_results['pooled_output'],"\n")
print(bert_results['sequence_output'],"\n")
#print(bert_results['encoder_outputs'],"\n")
print(bert_results['default'],"\n")

tf.Tensor(
[[-0.9129449  -0.4837616  -0.9126463  ... -0.7361232  -0.74970305
   0.9374017 ]
 [-0.8117082  -0.3607148  -0.28693053 ... -0.47226995 -0.59398293
   0.7808098 ]
 [-0.89365387 -0.42251703 -0.56231207 ... -0.29627907 -0.73115927
   0.9446686 ]
 ...
 [-0.8718355  -0.35126126 -0.5472081  ... -0.40263307 -0.6004087
   0.861716  ]
 [-0.71533084 -0.18132617  0.3592011  ...  0.14811358 -0.5463516
   0.7983961 ]
 [-0.7310761  -0.08176822  0.7194068  ...  0.39556634 -0.44054013
   0.7821696 ]], shape=(10, 768), dtype=float32) 

tf.Tensor(
[[[ 0.1789734   0.3894962   0.11169629 ... -0.36462843  0.43031937
    0.06069506]
  [ 0.7057359   0.39991453  0.19829264 ... -0.5117584   0.16248292
    0.11484808]
  [-0.69576734 -0.38325447  0.25077116 ...  0.14792907  0.63410795
    0.72287565]
  ...
  [ 0.0777894   0.23651862  0.73730916 ...  0.30605143 -0.01039323
   -0.14491874]
  [-0.02416935  0.35031292  0.7475932  ...  0.08545882 -0.1872074
   -0.01806601]
  [ 0.02683423  0.3449436   0.811

In [9]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']

<tf.Tensor: shape=(10, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True, 

In [11]:
bert_results['default'] == bert_results['pooled_output']

<tf.Tensor: shape=(10, 768), dtype=bool, numpy=
array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])>