In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
  print(f"GPU available: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available")

GPU available: Tesla T4


##Creating a Tensor

In [4]:
# using empty
a = torch.empty(2,4)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(9,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,9)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,6)

tensor([[0.1439, 0.4242, 0.7108, 0.4708, 0.3021, 0.8195],
        [0.7714, 0.0234, 0.1677, 0.2052, 0.7712, 0.5484]])

In [9]:
# manual_seed
torch.manual_seed(9100)
torch.rand(4,3)

tensor([[0.1688, 0.4687, 0.9634],
        [0.7861, 0.3242, 0.1276],
        [0.2517, 0.3610, 0.5811],
        [0.4834, 0.4305, 0.3833]])

In [10]:
# using tensor
torch.tensor([[1,2,3],[9,0,6]])

tensor([[1, 2, 3],
        [9, 0, 6]])

In [11]:
# arange
print("using arange ->", torch.arange(0,90,2))
print("\n")
# using linspace
print("using linspace ->", torch.linspace(7,10,10))
print("\n")
# using eye
print("using eye ->", torch.eye(9))
print("\n")
# using full
print("using full ->", torch.full((9, 3), 5))

using arange -> tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88])


using linspace -> tensor([ 7.0000,  7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,
         9.6667, 10.0000])


using eye -> tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1.]])


using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [12]:
a = torch.tensor([[[7,8,9]]])
a.shape

torch.Size([1, 1, 3])

In [13]:
torch.empty_like(a)

tensor([[[      334702800, 139249696129488,               0]]])

In [14]:
torch.zeros_like(a)

tensor([[[0, 0, 0]]])

In [15]:
torch.ones_like(a)

tensor([[[1, 1, 1]]])

In [16]:
torch.rand_like(a, dtype=torch.float32)

tensor([[[0.6182, 0.7636, 0.7849]]])

##Tensor DataTypes

In [17]:
# find data type
a.dtype

torch.int64

In [18]:
# assign data type
torch.tensor([6.0,2.0,4.0], dtype=torch.int32)

tensor([6, 2, 4], dtype=torch.int32)

In [19]:
torch.tensor([9,8,7], dtype=torch.float64)

tensor([9., 8., 7.], dtype=torch.float64)

In [20]:
# using to()
a.to(torch.float64)

tensor([[[7., 8., 9.]]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Maths Operations

In [21]:
# // Scalar Operations
# add
a + 2
# sub
a - 2
# multiply
a * 3
# div
a / 3
# int div
(a * 100)//3
# mod
((a * 100)//3)%2
# power
a**2

tensor([[[49, 64, 81]]])

In [22]:
# // Elemental Operations
a = torch.tensor([1,3,5])
b = torch.tensor([1,7,9])
c = torch.tensor([1, -2, 3, -4])
d = torch.tensor([1.3, -2.4, 3.6, -4.8])
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b
# abs
print(torch.abs(c))
# neg
print(torch.neg(c))
# round
print(torch.round(d))
# ceil
print(torch.ceil(d))
# floor
print(torch.floor(d))
# clamp
print(torch.clamp(d, min=2, max=9))

tensor([1, 2, 3, 4])
tensor([-1,  2, -3,  4])
tensor([ 1., -2.,  4., -5.])
tensor([ 2., -2.,  4., -4.])
tensor([ 1., -3.,  3., -5.])
tensor([2.0000, 2.0000, 3.6000, 2.0000])


In [23]:
# // Reduction Operations
e = torch.randint(size=(4,3), low=0, high=12, dtype=torch.float32)
# sum
print(torch.sum(e))
# sum along cols
print(torch.sum(e, dim=0))
# sum along rows
print(torch.sum(e, dim=1))
# median
print(torch.median(e))
# mean
print(torch.mean(e))
# mean along cols
print(torch.mean(e, dim=0))
# mean along rows
print(torch.mean(e, dim=1))
# min
print(torch.min(e))
# max
print(torch.max(e))
# prod
print(torch.prod(e))
# std dev
print(torch.std(e))
# var
print(torch.var(e))
# argmax
print(torch.argmax(e))
# argmin
print(torch.argmin(e))

tensor(93.)
tensor([28., 24., 41.])
tensor([25., 28., 13., 27.])
tensor(9.)
tensor(7.7500)
tensor([ 7.0000,  6.0000, 10.2500])
tensor([8.3333, 9.3333, 4.3333, 9.0000])
tensor(0.)
tensor(11.)
tensor(0.)
tensor(3.4935)
tensor(12.2045)
tensor(3)
tensor(6)


In [24]:
# // Matrix Operations
f = torch.randint(size=(8,3), low=0, high=7)
g = torch.randint(size=(3,8), low=7, high=11)
h = torch.randint(size=(6,6), low=8, high=14, dtype=torch.float64)
# matrix multiply
print(torch.matmul(f,g))
# dot prod
print(torch.dot(f[0],g[:,0]))
# trans
print(torch.transpose(f, 0, 1))
# det
print(torch.det(h))
# inv
print(torch.inverse(h))

tensor([[ 68,  56,  72,  61,  66,  79,  71,  65],
        [ 50,  42,  58,  46,  52,  60,  54,  48],
        [121, 105, 129, 124, 124, 145, 130, 125],
        [ 85,  77,  97,  95,  94, 106,  95,  92],
        [ 77,  70,  79,  89,  81,  94,  84,  86],
        [ 69,  56,  75,  59,  67,  80,  72,  64],
        [116,  98, 128, 110, 118, 138, 124, 114],
        [ 60,  56,  64,  73,  66,  75,  67,  69]])
tensor(68)
tensor([[1, 0, 5, 4, 6, 0, 2, 5],
        [2, 4, 4, 6, 1, 3, 6, 2],
        [5, 2, 6, 1, 3, 5, 6, 1]])
tensor(372.0000, dtype=torch.float64)
tensor([[ 3.3710e+00, -6.5081e+00,  2.0968e-01,  3.9516e-01, -6.9274e+00,
          8.9274e+00],
        [-8.9247e-01,  1.8817e+00, -2.5806e-01,  1.2903e-01,  1.7312e+00,
         -2.3978e+00],
        [-3.8172e-01,  8.1989e-01,  1.6129e-02, -8.0645e-03,  4.5430e-01,
         -7.8763e-01],
        [-3.0914e+00,  5.4005e+00, -8.0645e-02, -4.5968e-01,  6.2285e+00,
         -7.5618e+00],
        [ 2.6559e+00, -5.0215e+00,  2.2581e-01,  3.8710e-01

In [25]:
# // Comparison Operations
i = a
j = b
k = torch.randint(size=(5,3), low=5, high=10, dtype=torch.float32)
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# less than equal to
i <= j
# log
print(torch.log(k))
# exp
print(torch.exp(k))
# sqrt
print(torch.sqrt(k))
# sigmoid
print(torch.sigmoid(k))
# softmax
print(torch.softmax(k, dim=0))
# relu
print(torch.relu(k))

tensor([[2.0794, 1.9459, 2.1972],
        [1.6094, 2.0794, 1.9459],
        [1.9459, 2.1972, 1.6094],
        [2.0794, 1.6094, 2.1972],
        [2.1972, 1.7918, 1.6094]])
tensor([[2980.9580, 1096.6332, 8103.0840],
        [ 148.4132, 2980.9580, 1096.6332],
        [1096.6332, 8103.0840,  148.4132],
        [2980.9580,  148.4132, 8103.0840],
        [8103.0840,  403.4288,  148.4132]])
tensor([[2.8284, 2.6458, 3.0000],
        [2.2361, 2.8284, 2.6458],
        [2.6458, 3.0000, 2.2361],
        [2.8284, 2.2361, 3.0000],
        [3.0000, 2.4495, 2.2361]])
tensor([[0.9997, 0.9991, 0.9999],
        [0.9933, 0.9997, 0.9991],
        [0.9991, 0.9999, 0.9933],
        [0.9997, 0.9933, 0.9999],
        [0.9999, 0.9975, 0.9933]])
tensor([[0.1947, 0.0861, 0.4604],
        [0.0097, 0.2341, 0.0623],
        [0.0716, 0.6364, 0.0084],
        [0.1947, 0.0117, 0.4604],
        [0.5293, 0.0317, 0.0084]])
tensor([[8., 7., 9.],
        [5., 8., 7.],
        [7., 9., 5.],
        [8., 5., 9.],
        [9.,

In [26]:
# // Inplace Operations
m = a
n = b
# inplace "_"
m.add_(n)
m.relu_()
print(m)
print(n)

tensor([ 2, 10, 14])
tensor([1, 7, 9])


In [27]:
# // Copying Operations
print(a)
print(m)
print(id(a) == id(m))
# Just clone
m = a.clone()
print(a)
print(m)
print(id(a) == id(m))

tensor([ 2, 10, 14])
tensor([ 2, 10, 14])
True
tensor([ 2, 10, 14])
tensor([ 2, 10, 14])
False


In [29]:
# // GPU Usage
print(torch.cuda.is_available())
o = torch.device("cuda")
p = a.to(o)
print(p)
p = torch.rand((2,3), device=o)
print(p)

True
tensor([ 2, 10, 14], device='cuda:0')
tensor([[0.3134, 0.7894, 0.7076],
        [0.8145, 0.4157, 0.5936]], device='cuda:0')


In [37]:
# // Reshaping Tensors
print(p.shape)
print(p.reshape(1,6))
print(p.permute(1,0).shape)
print(p.unsqueeze(0).shape)
print(p.squeeze(1).shape)

torch.Size([2, 3])
tensor([[0.3134, 0.7894, 0.7076, 0.8145, 0.4157, 0.5936]], device='cuda:0')
torch.Size([3, 2])
torch.Size([1, 2, 3])
torch.Size([2, 3])


In [39]:
# // Numpy and PyTorch
b = a.numpy()
print(type(b))
b = torch.from_numpy(b)
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
